# Imagem base oficial do Python versão 3.11
FROM python:3.11

# Define o diretório de trabalho dentro do container
# Tudo vai rodar dentro de /app
WORKDIR /app

# Copia o arquivo de dependências para dentro do container
# (isso ajuda no cache do Docker)
COPY requirements.txt .

# Instala as dependências Python listadas no requirements.txt
RUN pip install -r requirements.txt

# Copia todo o código da pasta src para dentro do container (/app)
COPY src .

# Comando padrão executado quando o container inicia
# Executa o script principal de extração
CMD ["python3", "extract_and_load.py"]