version: 2

sources:
  - name: raw
    database: coingecko-494900
    schema: bronze
    tables:
      - name: crypto_list
      - name: current_market
      - name: overview
      - name: simple_price
      - name: trending


